version: "3.6"

services:
  worker:
    image: v2ray/official:latest
    container_name: v2ray-worker
    ports:
      - 20001:9999
    networks:
      - v2ray
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    volumes:
      - ./config/config.json:/etc/v2ray/config.json

networks:
  v2ray:
    driver: bridge
